### ISSUE TITLE
Actually setting KeepQuickSlotItems = false seems not to have any effect

### ISSUE THREAD

**Issue by FelixReuthlinger** [VMP-Valheim/DeathTweaks#2]
No clue why, but maybe this got lost during your changes from Traverse?

**Comment by sbtoonz** [comment]
Could also be in relation to EAQS update but will look into this thank you

**Comment by sbtoonz** [comment]
https://github.com/VMP-Valheim/DeathTweaks/blob/master/DeathTweaks/DeathTweaks.cs#L152

**Comment by sbtoonz** [comment]
code exists to use val will look further

**Comment by FelixReuthlinger** [comment]
> code exists to use val will look further

hm, ok, but somehow doesnt want to work, tested on test server, should be easy to replicate

**Comment by FelixReuthlinger** [comment]
same as #3
