### ISSUE TITLE
Ores in Hotbar not dropped

### ISSUE THREAD

**Issue by FelixReuthlinger** [VMP-Valheim/DeathTweaks#3]
Maybe this is due to priority, but actually it should drop items that are selected to be dropped from hotbar, even if KeepHotbarItems = true afaik

**Comment by sbtoonz** [comment]
KeepHotBarItems = true supercedes the dropmats

**Comment by sbtoonz** [comment]
https://github.com/VMP-Valheim/DeathTweaks/blob/master/DeathTweaks/DeathTweaks.cs#L172
current programmed behavior this is expected

**Comment by FelixReuthlinger** [comment]
> https://github.com/VMP-Valheim/DeathTweaks/blob/master/DeathTweaks/DeathTweaks.cs#L172
> current programmed behavior this is expected

can we change it? ;)
Since you can put ores into the hotbar do /killme to transport them to your bed ...

**Comment by sbtoonz** [comment]
Sure just un nest the if statement so that item drop happens before hotbar check maybe?

TODO

**Comment by FelixReuthlinger** [comment]
retested today, it actually works fine, idk why not yesterday or why not picked up config properly...

**Comment by sbtoonz** [comment]
9222ba0f623fe44741b57bc12389698b887eb608

you think this has any relation?

**Comment by FelixReuthlinger** [comment]
> [9222ba0](https://github.com/VMP-Valheim/DeathTweaks/commit/9222ba0f623fe44741b57bc12389698b887eb608)
> 
> you think this has any relation?

not that I could say - maybe it was just some config hickup
